[build]
  functions = "functions"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login-proxy"
  status = 200

[[redirects]]
  from = "/api/verify"
  to = "/.netlify/functions/verify-proxy"
  status = 200

[[redirects]]
  from = "/search/*"
  to = "/.netlify/functions/proxy"
  status = 200
  query = {url = ":url"}
